CREATE DATABASE ONLINE_STORE;
USE ONLINE_STORE;

CREATE TABLE USER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCT_REVIEW (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT(255) NOT NULL,
    USER_ID INT(255) NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

INSERT INTO USER (USERNAME, PASSWORD, ADDRESS) VALUES 
('admin', 'admin', 'test');